- name: install k3s essentials on k3s_cluster
  hosts: k3s_cluster
  tasks:
    - name: install nfs-common
      apt:
        name: nfs-common
        state: present
        update_cache: true
      become: true